version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: simple_form
    versions:
    - 5.0.3
  - dependency-name: geocoder
    versions:
    - 1.6.1
  - dependency-name: rails
    versions:
    - 5.0.7.2
  - dependency-name: devise
    versions:
    - 4.7.1
  - dependency-name: jquery-rails
    versions:
    - 4.3.4
